---
title: 'Mammal trait summary'
output: 
  html_document:
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load packages
library(here)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(patchwork)

# set ggplot themes
theme_set(theme_pubclean())
```

```{r}
df <- readRDS(here("data-clean/LPI_pantheria.rds")) %>% 
  filter(Class == "Mammalia")
```

### Distribution of the traits

```{r,fig.show='hold', message=FALSE, warning = FALSE, fig.height = 4, fig.width=9}
A <- ggplot(df) +
  geom_histogram(aes(x = log(AdultBodyMass_g)), 
                 binwidth = 2, col = "white",
                 fill = "navyblue", alpha = .6) +
  labs(x = "log Body Mass (g)")
B <- ggplot(df) +
  geom_histogram(aes(x = TrophicLevel), 
                 binwidth = 1, col = "white",
                 fill = "firebrick", alpha = .6) +
  labs(x = "Trophic Level")
C <- ggplot(df) +
  geom_histogram(aes(x = MaxLongevity_m), 
                 bins = 15, col = "white",
                 fill = "darkgreen", alpha = .6) +
  labs(x = "Max Longevity")
A + B + C
```

```{r,fig.show='hold', message=FALSE, warning = FALSE, fig.height = 4, fig.width=9, include = FALSE}
A <- ggplot(df) +
  geom_density(aes(x = log(AdultBodyMass_g)), 
               col = "white",
               fill = "navyblue", alpha = .6) +
  labs(x = "log Body Mass (g)")
B <- ggplot(df) +
  geom_histogram(aes(x = TrophicLevel), 
                 binwidth = 1, col = "white",
                 fill = "firebrick", alpha = .6) +
  labs(x = "Trophic Level")
C <- ggplot(df) +
  geom_density(aes(x = MaxLongevity_m), 
               col = "white",
               fill = "darkgreen", alpha = .6) +
  labs(x = "Max Longevity")
A + B + C
```


### Relationship with average lambdas

```{r, warning = F}
lpi <- readRDS("~/Documents/GitHub/LPD/example_code/data/CIEE_LPI_combined.rds")

df_plot <- full_join(lpi, df, by = "Binomial") %>% filter(Class.x == "Mammalia")

A <- ggplot(df_plot, 
            aes(x = log(AdultBodyMass_g), y = avlambda) ) + 
  geom_point() +
  labs(x = "log Body Mass (g)")

B <- ggplot(df_plot, aes(x = as.factor(TrophicLevel), y = avlambda, 
                         fill = as.factor(TrophicLevel)) ) + 
  geom_boxplot() +
  labs(x = "Trophic Level")

C <- ggplot(df_plot, aes(x = MaxLongevity_m, y = avlambda) ) + 
  geom_point() +
  labs(x = "Max Longevity")

A + B + C
```

