---
title: "Relationships between population change (lambdas) and traits for Birds"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    theme: paper
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(here)
library(dplyr)
library(lme4)
library(performance)
library(sjPlot)
library(ggplot2)
library(visdat)
library(patchwork)

# set a ggplot theme for all plots
theme_set(ggpubr::theme_pubr())

model_data = read.csv(here("scripts/CIEE_model_data.csv"), as.is = T)
model_data = model_data %>%
  filter(Replicate == 0)

trait_data = data.table::fread(here("data-clean/traits-all.csv"))

# join the datasets
df_join = left_join(model_data, trait_data, by = "Binomial")
# convert trophic level to factor
df_join$TrophicLevel <- factor(df_join$TrophicLevel)
```

## Birds in Canada

```{r}
bird_df <- readRDS(here("data-clean", "LPI_birds_traits.rds"))
```

```{r}
# check missing values 
vis_miss(bird_df)
```

```{r}
bird_tidy <- model_data %>%
  left_join(bird_df, by = "Binomial") %>%
  filter(Class == "Birds") %>%
  rename(
    body_size = mean_adult_body_mass_g,
    max_lifespan = mean_max_longevity_y, 
    lifespan = mean_longevity_y, 
  )

bird_traits <- c(
  "hwi", 
  "range_size", 
  "diet", 
  "body_size",
  "max_lifespan",
  "lifespan"
  ) 

# ensure complete cases for all traits 
# helps with comparing AIC values 
bird_tidy <- bird_tidy[complete.cases(bird_tidy[, bird_traits]), ]
```

```{r}
# check missing values 
vis_miss(bird_tidy)
```

```{r}
# null model
m0_b = lmer(avlambda ~ (1|Binomial), data = bird_tidy)
m1_b = lmer(avlambda ~ System + (1|Binomial), data = bird_tidy)

# adding traits

# body size only
# class should be in each model because body size is normalised within classes
m2_b = lmer(avlambda ~ log10(body_size) + (1|Binomial),  data = bird_tidy)
m3_b = lmer(avlambda ~ log10(body_size) + System + (1|Binomial),  data = bird_tidy)
m4_b = lmer(avlambda ~ System*log10(body_size) + (1|Binomial),  data = bird_tidy)

# hwi
m15_b <- lmer(avlambda ~ hwi + (1|Binomial), data = bird_tidy)

# trophic level only
m5_b = lmer(avlambda ~ diet + (1|Binomial),  data = bird_tidy)
m6_b = lmer(avlambda ~ diet + System + (1|Binomial),  data = bird_tidy)
m7_b = lmer(avlambda ~ System*diet + (1|Binomial),  data = bird_tidy)

# lifespan only
m8_b = lmer(avlambda ~ lifespan + (1|Binomial),  data = bird_tidy)
m9_b = lmer(avlambda ~ lifespan + System + (1|Binomial),  data = bird_tidy)
m10_b = lmer(avlambda ~ System*lifespan + (1|Binomial),  data = bird_tidy)

# all three traits
m11_b = lmer(avlambda ~ log10(body_size) + diet + (1|Binomial),  data = bird_tidy)
m12_b = lmer(avlambda ~ log10(body_size) + lifespan + (1|Binomial),  data = bird_tidy)
m13_b = lmer(avlambda ~ diet + lifespan + (1|Binomial),  data = bird_tidy)
m14_b = lmer(avlambda ~ log10(body_size) + diet + lifespan + (1|Binomial),  data = bird_tidy)
```


```{r}
compare_performance(m0_b, m1_b, m2_b, m3_b, # no traits
                    m4_b, m5_b, m6_b, m7_b, # body size
                    m8_b, m9_b, m10_b, m11_b, m12_b, # trophic level
                    m13_b, m14_b, m15_b, # variations of 2 or 3 traits
                    rank = FALSE) %>%
  kableExtra::kable() %>% kableExtra::kable_styling("striped")
```
